apiVersion: v1
kind: Secret
metadata:
  name: blog-postgresql
  namespace: default
  labels:
    app: blog-postgresql
type: Opaque
data:
  postgresql-password: MjZlZTdjYjhkNjgwMTZkMzg0MGQ1ZWZjZWI5NWUxZTA1YTI5NWVjZGExNTM3MWU1YWQ1ZjZiOTc4Mjgz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-postgresql
  template:
    metadata:
      labels:
        app: blog-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:13.4
          env:
            - name: POSTGRES_USER
              value: blog
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-postgresql
  namespace: default
spec:
  selector:
    app: blog-postgresql
  ports:
    - port: 5432
