commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-postgresql.yml
  - gateway-k8s/gateway-prometheus-sm.yml
  - blog-k8s/blog-deployment.yml
  - blog-k8s/blog-service.yml
  - blog-k8s/blog-postgresql.yml
  - blog-k8s/blog-prometheus-sm.yml
  - store-k8s/store-deployment.yml
  - store-k8s/store-service.yml
  - store-k8s/store-postgresql.yml
  - store-k8s/store-prometheus-sm.yml
  # monitoring prometheus
  - monitoring-k8s/jhipster-prometheus-cr.yml
  - monitoring-k8s/jhipster-prometheus-crd.yml
  - monitoring-k8s/jhipster-grafana.yml
  - monitoring-k8s/jhipster-grafana-dashboard.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
