apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: genvitatest/gateway
      context: ../gateway
      jib: {}
    - image: genvitatest/blog
      context: ../blog
      jib: {}
    - image: genvitatest/store
      context: ../store
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
