# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGZmZjhlMzM1ZGYyNzMxZjIwOGQ1OTVlNDVmODI5Mzk5ZDlhYjQxMTI3ZjE2NmQyMjQ0OWZkNjAwYWVlMmVjZDM0MzE1Yjg5NzhlYTNmNmE5M2ZkODE3NDk0NzU5N2NlYzI4YTM3NGMxMjM1ZTdkNzU0NGM1ZjhiMWIyN2E2ODM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
